/* Automatically generated file - DO NOT EDIT */
static const char psz_license[] =
"                    GNU GENERAL PUBLIC LICENSE\n"
"                       Version 2, June 1991\n"
"\n"
" Copyright (C) 1989, 1991 Free Software Foundation, Inc.\n"
" 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA\n"
" Everyone is permitted to copy and distribute verbatim copies\n"
" of this license document, but changing it is not allowed.\n"
"\n"
"                            Preamble\n"
"\n"
"  The licenses for most software are designed to take away your\n"
"freedom to share and change it.  By contrast, the GNU General Public\n"
"License is intended to guarantee your freedom to share and change free\n"
"software--to make sure the software is free for all its users.  This\n"
"General Public License applies to most of the Free Software\n"
"Foundation's software and to any other program whose authors commit to\n"
"using it.  (Some other Free Software Foundation software is covered by\n"
"the GNU Library General Public License instead.)  You can apply it to\n"
"your programs, too.\n"
"\n"
"  When we speak of free software, we are referring to freedom, not\n"
"price.  Our General Public Licenses are designed to make sure that you\n"
"have the freedom to distribute copies of free software (and charge for\n"
"this service if you wish), that you receive source code or can get it\n"
"if you want it, that you can change the software or use pieces of it\n"
"in new free programs; and that you know you can do these things.\n"
"\n"
"  To protect your rights, we need to make restrictions that forbid\n"
"anyone to deny you these rights or to ask you to surrender the rights.\n"
"These restrictions translate to certain responsibilities for you if you\n"
"distribute copies of the software, or if you modify it.\n"
"\n"
"  For example, if you distribute copies of such a program, whether\n"
"gratis or for a fee, you must give the recipients all the rights that\n"
"you have.  You must make sure that they, too, receive or can get the\n"
"source code.  And you must show them these terms so they know their\n"
"rights.\n"
"\n"
"  We protect your rights with two steps: (1) copyright the software, and\n"
"(2) offer you this license which gives you legal permission to copy,\n"
"distribute and/or modify the software.\n"
"\n"
"  Also, for each author's protection and ours, we want to make certain\n"
"that everyone understands that there is no warranty for this free\n"
"software.  If the software is modified by someone else and passed on, we\n"
"want its recipients to know that what they have is not the original, so\n"
"that any problems introduced by others will not reflect on the original\n"
"authors' reputations.\n"
"\n"
"  Finally, any free program is threatened constantly by software\n"
"patents.  We wish to avoid the danger that redistributors of a free\n"
"program will individually obtain patent licenses, in effect making the\n"
"program proprietary.  To prevent this, we have made it clear that any\n"
"patent must be licensed for everyone's free use or not licensed at all.\n"
"\n"
"  The precise terms and conditions for copying, distribution and\n"
"modification follow.\n"
"\n"
"                    GNU GENERAL PUBLIC LICENSE\n"
"   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n"
"\n"
"  0. This License applies to any program or other work which contains\n"
"a notice placed by the copyright holder saying it may be distributed\n"
"under the terms of this General Public License.  The \"Program\", below,\n"
"refers to any such program or work, and a \"work based on the Program\"\n"
"means either the Program or any derivative work under copyright law:\n"
"that is to say, a work containing the Program or a portion of it,\n"
"either verbatim or with modifications and/or translated into another\n"
"language.  (Hereinafter, translation is included without limitation in\n"
"the term \"modification\".)  Each licensee is addressed as \"you\".\n"
"\n"
"Activities other than copying, distribution and modification are not\n"
"covered by this License; they are outside its scope.  The act of\n"
"running the Program is not restricted, and the output from the Program\n"
"is covered only if its contents constitute a work based on the\n"
"Program (independent of having been made by running the Program).\n"
"Whether that is true depends on what the Program does.\n"
"\n"
"  1. You may copy and distribute verbatim copies of the Program's\n"
"source code as you receive it, in any medium, provided that you\n"
"conspicuously and appropriately publish on each copy an appropriate\n"
"copyright notice and disclaimer of warranty; keep intact all the\n"
"notices that refer to this License and to the absence of any warranty;\n"
"and give any other recipients of the Program a copy of this License\n"
"along with the Program.\n"
"\n"
"You may charge a fee for the physical act of transferring a copy, and\n"
"you may at your option offer warranty protection in exchange for a fee.\n"
"\n"
"  2. You may modify your copy or copies of the Program or any portion\n"
"of it, thus forming a work based on the Program, and copy and\n"
"distribute such modifications or work under the terms of Section 1\n"
"above, provided that you also meet all of these conditions:\n"
"\n"
"    a) You must cause the modified files to carry prominent notices\n"
"    stating that you changed the files and the date of any change.\n"
"\n"
"    b) You must cause any work that you distribute or publish, that in\n"
"    whole or in part contains or is derived from the Program or any\n"
"    part thereof, to be licensed as a whole at no charge to all third\n"
"    parties under the terms of this License.\n"
"\n"
"    c) If the modified program normally reads commands interactively\n"
"    when run, you must cause it, when started running for such\n"
"    interactive use in the most ordinary way, to print or display an\n"
"    announcement including an appropriate copyright notice and a\n"
"    notice that there is no warranty (or else, saying that you provide\n"
"    a warranty) and that users may redistribute the program under\n"
"    these conditions, and telling the user how to view a copy of this\n"
"    License.  (Exception: if the Program itself is interactive but\n"
"    does not normally print such an announcement, your work based on\n"
"    the Program is not required to print an announcement.)\n"
"\n"
"These requirements apply to the modified work as a whole.  If\n"
"identifiable sections of that work are not derived from the Program,\n"
"and can be reasonably considered independent and separate works in\n"
"themselves, then this License, and its terms, do not apply to those\n"
"sections when you distribute them as separate works.  But when you\n"
"distribute the same sections as part of a whole which is a work based\n"
"on the Program, the distribution of the whole must be on the terms of\n"
"this License, whose permissions for other licensees extend to the\n"
"entire whole, and thus to each and every part regardless of who wrote it.\n"
"\n"
"Thus, it is not the intent of this section to claim rights or contest\n"
"your rights to work written entirely by you; rather, the intent is to\n"
"exercise the right to control the distribution of derivative or\n"
"collective works based on the Program.\n"
"\n"
"In addition, mere aggregation of another work not based on the Program\n"
"with the Program (or with a work based on the Program) on a volume of\n"
"a storage or distribution medium does not bring the other work under\n"
"the scope of this License.\n"
"\n"
"  3. You may copy and distribute the Program (or a work based on it,\n"
"under Section 2) in object code or executable form under the terms of\n"
"Sections 1 and 2 above provided that you also do one of the following:\n"
"\n"
"    a) Accompany it with the complete corresponding machine-readable\n"
"    source code, which must be distributed under the terms of Sections\n"
"    1 and 2 above on a medium customarily used for software interchange; or,\n"
"\n"
"    b) Accompany it with a written offer, valid for at least three\n"
"    years, to give any third party, for a charge no more than your\n"
"    cost of physically performing source distribution, a complete\n"
"    machine-readable copy of the corresponding source code, to be\n"
"    distributed under the terms of Sections 1 and 2 above on a medium\n"
"    customarily used for software interchange; or,\n"
"\n"
"    c) Accompany it with the information you received as to the offer\n"
"    to distribute corresponding source code.  (This alternative is\n"
"    allowed only for noncommercial distribution and only if you\n"
"    received the program in object code or executable form with such\n"
"    an offer, in accord with Subsection b above.)\n"
"\n"
"The source code for a work means the preferred form of the work for\n"
"making modifications to it.  For an executable work, complete source\n"
"code means all the source code for all modules it contains, plus any\n"
"associated interface definition files, plus the scripts used to\n"
"control compilation and installation of the executable.  However, as a\n"
"special exception, the source code distributed need not include\n"
"anything that is normally distributed (in either source or binary\n"
"form) with the major components (compiler, kernel, and so on) of the\n"
"operating system on which the executable runs, unless that component\n"
"itself accompanies the executable.\n"
"\n"
"If distribution of executable or object code is made by offering\n"
"access to copy from a designated place, then offering equivalent\n"
"access to copy the source code from the same place counts as\n"
"distribution of the source code, even though third parties are not\n"
"compelled to copy the source along with the object code.\n"
"\n"
"  4. You may not copy, modify, sublicense, or distribute the Program\n"
"except as expressly provided under this License.  Any attempt\n"
"otherwise to copy, modify, sublicense or distribute the Program is\n"
"void, and will automatically terminate your rights under this License.\n"
"However, parties who have received copies, or rights, from you under\n"
"this License will not have their licenses terminated so long as such\n"
"parties remain in full compliance.\n"
"\n"
"  5. You are not required to accept this License, since you have not\n"
"signed it.  However, nothing else grants you permission to modify or\n"
"distribute the Program or its derivative works.  These actions are\n"
"prohibited by law if you do not accept this License.  Therefore, by\n"
"modifying or distributing the Program (or any work based on the\n"
"Program), you indicate your acceptance of this License to do so, and\n"
"all its terms and conditions for copying, distributing or modifying\n"
"the Program or works based on it.\n"
"\n"
"  6. Each time you redistribute the Program (or any work based on the\n"
"Program), the recipient automatically receives a license from the\n"
"original licensor to copy, distribute or modify the Program subject to\n"
"these terms and conditions.  You may not impose any further\n"
"restrictions on the recipients' exercise of the rights granted herein.\n"
"You are not responsible for enforcing compliance by third parties to\n"
"this License.\n"
"\n"
"  7. If, as a consequence of a court judgment or allegation of patent\n"
"infringement or for any other reason (not limited to patent issues),\n"
"conditions are imposed on you (whether by court order, agreement or\n"
"otherwise) that contradict the conditions of this License, they do not\n"
"excuse you from the conditions of this License.  If you cannot\n"
"distribute so as to satisfy simultaneously your obligations under this\n"
"License and any other pertinent obligations, then as a consequence you\n"
"may not distribute the Program at all.  For example, if a patent\n"
"license would not permit royalty-free redistribution of the Program by\n"
"all those who receive copies directly or indirectly through you, then\n"
"the only way you could satisfy both it and this License would be to\n"
"refrain entirely from distribution of the Program.\n"
"\n"
"If any portion of this section is held invalid or unenforceable under\n"
"any particular circumstance, the balance of the section is intended to\n"
"apply and the section as a whole is intended to apply in other\n"
"circumstances.\n"
"\n"
"It is not the purpose of this section to induce you to infringe any\n"
"patents or other property right claims or to contest validity of any\n"
"such claims; this section has the sole purpose of protecting the\n"
"integrity of the free software distribution system, which is\n"
"implemented by public license practices.  Many people have made\n"
"generous contributions to the wide range of software distributed\n"
"through that system in reliance on consistent application of that\n"
"system; it is up to the author/donor to decide if he or she is willing\n"
"to distribute software through any other system and a licensee cannot\n"
"impose that choice.\n"
"\n"
"This section is intended to make thoroughly clear what is believed to\n"
"be a consequence of the rest of this License.\n"
"\n"
"  8. If the distribution and/or use of the Program is restricted in\n"
"certain countries either by patents or by copyrighted interfaces, the\n"
"original copyright holder who places the Program under this License\n"
"may add an explicit geographical distribution limitation excluding\n"
"those countries, so that distribution is permitted only in or among\n"
"countries not thus excluded.  In such case, this License incorporates\n"
"the limitation as if written in the body of this License.\n"
"\n"
"  9. The Free Software Foundation may publish revised and/or new versions\n"
"of the General Public License from time to time.  Such new versions will\n"
"be similar in spirit to the present version, but may differ in detail to\n"
"address new problems or concerns.\n"
"\n"
"Each version is given a distinguishing version number.  If the Program\n"
"specifies a version number of this License which applies to it and \"any\n"
"later version\", you have the option of following the terms and conditions\n"
"either of that version or of any later version published by the Free\n"
"Software Foundation.  If the Program does not specify a version number of\n"
"this License, you may choose any version ever published by the Free Software\n"
"Foundation.\n"
"\n"
"  10. If you wish to incorporate parts of the Program into other free\n"
"programs whose distribution conditions are different, write to the author\n"
"to ask for permission.  For software which is copyrighted by the Free\n"
"Software Foundation, write to the Free Software Foundation; we sometimes\n"
"make exceptions for this.  Our decision will be guided by the two goals\n"
"of preserving the free status of all derivatives of our free software and\n"
"of promoting the sharing and reuse of software generally.\n"
"\n"
"                            NO WARRANTY\n"
"\n"
"  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY\n"
"FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN\n"
"OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n"
"PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED\n"
"OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n"
"MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS\n"
"TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE\n"
"PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,\n"
"REPAIR OR CORRECTION.\n"
"\n"
"  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n"
"WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR\n"
"REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,\n"
"INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\n"
"OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED\n"
"TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY\n"
"YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER\n"
"PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n"
"POSSIBILITY OF SUCH DAMAGES.\n"
"\n"
"                     END OF TERMS AND CONDITIONS\n"
"\n"
"            How to Apply These Terms to Your New Programs\n"
"\n"
"  If you develop a new program, and you want it to be of the greatest\n"
"possible use to the public, the best way to achieve this is to make it\n"
"free software which everyone can redistribute and change under these terms.\n"
"\n"
"  To do so, attach the following notices to the program.  It is safest\n"
"to attach them to the start of each source file to most effectively\n"
"convey the exclusion of warranty; and each file should have at least\n"
"the \"copyright\" line and a pointer to where the full notice is found.\n"
"\n"
"    <one line to give the program's name and a brief idea of what it does.>\n"
"    Copyright (C) <year>  <name of author>\n"
"\n"
"    This program is free software; you can redistribute it and/or modify\n"
"    it under the terms of the GNU General Public License as published by\n"
"    the Free Software Foundation; either version 2 of the License, or\n"
"    (at your option) any later version.\n"
"\n"
"    This program is distributed in the hope that it will be useful,\n"
"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"    GNU General Public License for more details.\n"
"\n"
"    You should have received a copy of the GNU General Public License\n"
"    along with this program; if not, write to the Free Software\n"
"    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA\n"
"\n"
"\n"
"Also add information on how to contact you by electronic and paper mail.\n"
"\n"
"If the program is interactive, make it output a short notice like this\n"
"when it starts in an interactive mode:\n"
"\n"
"    Gnomovision version 69, Copyright (C) year name of author\n"
"    Gnomovision comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n"
"    This is free software, and you are welcome to redistribute it\n"
"    under certain conditions; type `show c' for details.\n"
"\n"
"The hypothetical commands `show w' and `show c' should show the appropriate\n"
"parts of the General Public License.  Of course, the commands you use may\n"
"be called something other than `show w' and `show c'; they could even be\n"
"mouse-clicks or menu items--whatever suits your program.\n"
"\n"
"You should also get your employer (if you work as a programmer) or your\n"
"school, if any, to sign a \"copyright disclaimer\" for the program, if\n"
"necessary.  Here is a sample; alter the names:\n"
"\n"
"  Yoyodyne, Inc., hereby disclaims all copyright interest in the program\n"
"  `Gnomovision' (which makes passes at compilers) written by James Hacker.\n"
"\n"
"  <signature of Ty Coon>, 1 April 1989\n"
"  Ty Coon, President of Vice\n"
"\n"
"This General Public License does not permit incorporating your program into\n"
"proprietary programs.  If your program is a subroutine library, you may\n"
"consider it more useful to permit linking proprietary applications with the\n"
"library.  If this is what you want to do, use the GNU Library General\n"
"Public License instead of this License.\n"
;
static const char psz_thanks[] =
"The VideoLAN team would like to thank the following donators:\n"
"\n"
"Julian Cain, who made a $1000 donation\n"
"The French website MacBidouille gave €500 to help us buy a PowerMac G5\n"
"The French magazine à vos MAC gave €500 to help us buy a PowerMac G5\n"
"Laurent Dupuy, who made a €540 donation\n"
"The French company Cybervia (Actech) gave €2000 to pay for webserver hosting\n"
"\n"
"\n"
"The VideoLAN team would like to thank the following contributors:\n"
"\n"
"Adam Sampson - libFLAC >= 1.1.3 API support\n"
"Adem Gunes aka Yuksel Yildirim - Turkish localisation \n"
"Adrien Grand - Java and VLM corrections\n"
"Adrien Maglo - VU meter and various fixes\n"
"Alan Wright - Forum help and support\n"
"Alex Antropoff - RFC3016 (LATM) RTP packetizer extension, MMS fixes\n"
"Alex Izvorski - some more x264 options\n"
"Alexander Didebulidze - Georgian localization\n"
"Alexander Gall - Solaris fixes and CDDB fixes\n"
"Alexey Lugin - Ukrainian translation\n"
"Alexey Salmin - Russian localisation\n"
"Alexis Ballier - Additional options in configure\n"
"Alexis de Lattre - Documentation, packaging, IGMPv3 support and various fixes\n"
"Amanpreet Singh Alam - Punjabi translation\n"
"Andrea Guzzo - dc1394 firewire support\n"
"André de Barros Martins Ribeiro - Brazilian portuguese localization\n"
"Andre Pang - Annodex support\n"
"André Weber - Qt4, AAC ordering, Win32 threads patches, video filter module for thehomebrewAmbiLight (AtmoLight)\n"
"Andres Krapf - FreeBSD port and tests, KDE interface\n"
"Andrew Zaikin - Config saving fixes\n"
"Andrey Brilevskiy - Russian translation\n"
"Andrey Wolk - Russian translation\n"
"Andy Lindsay - fixes in the TS demux\n"
"Anh Phan - Vietnamese translation\n"
"Animesh Swar - Nepalese translation\n"
"Anthony Loiseau - Various fixes\n"
"Antoine Lejeune - Maemo port\n"
"Ara Bextiyar - Sorani (Kurdish) translation\n"
"Arai/Fujisawa Tooru - OpenGL-based Screen Input Module for Mac OS X\n"
"Ari Constâncio - Portuguese localisation\n"
"Arkadiusz Lipiec - Polish translation\n"
"Arkadiusz Miskiewicz - autoconf and Makefile patches\n"
"Arnaud Gomes-do-Vale - autoconf patches\n"
"Arwed v. Merkatz - Gamma correction for adjust filter\n"
"Audrey Prevost - Help on french translation\n"
"Aurélien Nephtali - Patch for modules/stream_output/rtp.c proper test for NULL. Fix crash in video filters error handling code in transcode. Fix telnet crash.\n"
"Barak Ori - Bidi fixes\n"
"Barry Wardell - Qt4 patch.\n"
"Basil Achermann - Patch to handle esc and space key events from VLCControl (OSX)\n"
"Bayarsaikhan Enkhtaivan Баярсайхан Энхтайван - Mongolian translation\n"
"Benjamin Mironer - Mac OS X fixes\n"
"Benoit Steiner - MPEG system input, network input\n"
"Bernie Purcell - MKV USF subtitles support,HTML tags for subtitles and subtitles renderer enhancements\n"
"Bill - memleak fixes\n"
"Bill Eldridge - documentation\n"
"Bill C. Riemers - http access fixes\n"
"Bob Maguire - addition of some controls to the OSX interface\n"
"Brian C. Wiles - vlm schedule date fix\n"
"Brian Johnson - interface fix\n"
"Brian Raymond - Quicktime 404 error on RTSP SETUP fix\n"
"Brian Robb - win32 CD/DVD drive detection in wx, bug fixes\n"
"Brieuc Jeunhomme - bug fixes\n"
"Bruno Queirós - Portuguese localisation\n"
"Bruno Vella - Italian localization\n"
"Carlo Calabrò - Italian localization\n"
"Carsten Gottbehüt - v4l hotplug fix\n"
"Carsten Haitzler - x11 fullscreen fix\n"
"Cédric Cocquebert - Misc opengl effects for the OpenGL Video Output. \"Panoramix\" video filter for image walls with automatic attenuation. Fix on sharpen filter.\n"
"Charles Hordis - QAM modulation on ATSC\n"
"Chris Clepper - OpenGL fix\n"
"Christian Henz - libupnp service discovery plugin, CyberLink UPnP fixes\n"
"Christof Baumgaertner - dbox web intf\n"
"Christophe Burgalat - XVMC (cle266) patch for VIA boards\n"
"Christopher Johnson - Qt fix in vlc.spec\n"
"Cian Duffy - BeOS builds and maintener\n"
"Colin Simmonds - compile fix for Mac OS X\n"
"Cristian Secară - Romanian l10n\n"
"Cyril Mathé - WebPlugin features and improvements\n"
"Damian Ivereigh - ac3dec uninitialized data structure fix\n"
"Damien Fouilleul - DirectShow input improvements\n"
"Daniel Dreibrodt, aka aLtgLasS - VLC 0.8.5 default skin, skins, design and help on the forum and the wiki\n"
"Daniel Fischer - Shoutcast output support\n"
"Daniel Nylander - Swedish translation\n"
"Daniel Stränger - M3U, xtag and playlist improvements. Meta information core fixes. XSPF playlist support\n"
"Danko Dolch - Icons and Design for Qt4 Interface\n"
"Danny Wood - Surround PulseAudio support.\n"
"David Flynn - Dirac video codec\n"
"David Kennedy - X11 fullscreen patch\n"
"David J LaBarre \"DJ\" - Forum help, moderation and support\n"
"David Thiel - security audit and report\n"
"David Weber - Mac OS X interface design & graphics (v0.5.0)\n"
"Davor Orel - Mac OS X icons\n"
"Dennis Lou - ATSC support in the DVB module, MPEG2 support in the v4l2 module\n"
"Dennis van Amerongen - x264 options unification\n"
"Dermot McGahon - Bug fixes, RC interface loop and repeat\n"
"Diego Petteno - remove usage of internal ffmpeg symbols, configure fixes\n"
"DirektX - Hungarian translation\n"
"Dominic Spitaler - Mac OS X Document Icons (v1.0)\n"
"Dominique Leuenberger - SUSE Packaging, some patches\n"
"Douglas West - dynamicoverlay patch\n"
"Dugal Harris - DirectShow fixes and MJPEG patches\n"
"Dylan Aïssi - French translation\n"
"Dylan Yudaken - hotkeys patch\n"
"Emmanuel Blindauer - aRts audio output\n"
"Enrico Gueli - Brightness threshold in adjust video filter\n"
"Enrique Osuna - Various bug fixes in libvlc. Major Mac OS X Framework improvements.\n"
"Eren Türkay - Speex boundary checks and security fix\n"
"Eric Adler - Forum help and support, strings review\n"
"Eric Dudiak - Mac OS X Interface rework (GSoC 2008)\n"
"Eric Lassauge -- French translation\n"
"Espen Skoglund - FreeBSD autoconf and Makefile patches\n"
"Ethan C. Baldridge - directory browsing code\n"
"Eurodata Computer Club - VLC icon design (v0.8.4)\n"
"Farzaneh Sarafraz - Persian localisation\n"
"Fouzia Bourai - Arabic localisation\n"
"François Seingier - TTL setting in the wx stream output dialog\n"
"Frank Chao - Chinese Traditional translation\n"
"Frans van Veen - Mozilla plugin toolbar\n"
"Fumio Nakayama - Japanese translation\n"
"Gabor Kelemen - Hungarian translation\n"
"Geoffrey Roussel - Christmas easter egg Artwork\n"
"Geoffroy Couprie - Podcast fix\n"
"Georgi Chorbadzhiyski - HTTP access error handling fix, ASF output patches.\n"
"Gisle Vanem  - gettimeoffay under win32\n"
"Glen Gray - RTSP keepalive\n"
"Goetz Waschk - Mandrake packages\n"
"Gorana Milicevic - Serbian localisation\n"
"Greg Farrell - rc interface \"enqueue\" command\n"
"Gregory Hazel - wxWidgets fixes and improvements\n"
"Haakon Meland Eriksen - Norwegian translation\n"
"Han HoJoong - Korean translation\n"
"Hang Su wpl and zpl support\n"
"Hans Lambermont - Syslog improvements\n"
"Hans-Peter Jansen - patch for module options handling\n"
"Hannes Domani - Qt4 interfaces patches\n"
"Harris Dugal - ActiveX bug fixes\n"
"Harry Sintonen - fix for MKV demuxer\n"
"Igor Helman - VLM msecseek command\n"
"Ilkka Ollakka - SDP bitrate patch, various VLM fixes, transcode afilter/vfilter fix, qt4 interface patches\n"
"Isaac Osunkunle - - Spatializer (GSoc 2007)\n"
"Ivo Ivanov - Bulgarian translation\n"
"Jamil Ahmed - Bengali translation\n"
"Jan David Mol - Suggested some flags for ffmpeg building\n"
"Jan Gerber - patch theora decoding aspect ratio\n"
"Jan Van Boghout - iTunes like slider for OSX intf\n"
"Jarmo Torvinen - rawaudio demuxer\n"
"Jasper Alias <j.alias at student.hhs.nl>- Mozilla plugin toolbar\n"
"Javier Varela - Spanish translation\n"
"Jean-Alexis Montignies - coreaudio multiple streams fix\n"
"Jean-Baptiste Le Stang - Equalizer-GUI-fixes (OSX), Universal Binary Script\n"
"Jean-François Massol - Qt4 Sout work\n"
"Jean-Philippe André - Qt bugs and improvements, various bugfixes, Zip access module\n"
"Jean-Philippe Grimaldi - bug fixes\n"
"Jean-Pierre Kuypers - French translation\n"
"Jeffrey Baker - port of the ALSA plugin to the ALSA 1.0 API\n"
"Jeroen Massar - IPv6 hostname resolution fix\n"
"Jérôme Guilbaud - Update of the WinAmp 5 VLC skin\n"
"Joel Arvidsson - Swedish translation\n"
"Joeri van Dooren - OS X icon (v0.4.0)\n"
"Johannes Buchner - Hotkeys for zoom\n"
"Johen Michael Zorko - fix for delay issues in udp sout\n"
"Johnathan Rosser - Dirac video codec\n"
"John Dalgliesh - macosx interface playlist fix\n"
"John Paul Lorenti - ALSA device selection patch\n"
"Jonas Larsen - Danish translation\n"
"Jörg - VLM seek/show media functions\n"
"Joseph Tulou - small dc1394 patch, image demuxer\n"
"Jouni Kähkönen - Finnish translation\n"
"Julien Blache - disc ejection code\n"
"Julien Bouquillon - Forum support and a VLC JS library\n"
"Julien Plissonneau Duquène - JACK audio input module \n"
"Julien Robert - DTS to SPDIF fixes.\n"
"K. Staring - RTSP rewind and fast-forward support\n"
"Kai Hermann - German translation\n"
"Kang Jeong-Hee - Korean translation\n"
"Kenneth Ostby - Audioscrobbler plugin\n"
"Kenneth Self - BDA capture plugin\n"
"Kevin H. Patterson - Theora framesize calculation \n"
"Koehler, Vitally -  solves the problem of audio packet losses by the playback of MPEG2 transport stream.\n"
"Konstanty Bialkowski - improvements on mod files support\n"
"kty0ne - WinAmp 5 skin for VLC\n"
"Lahiru Lakmal Priyadarshana - Qt4 patch\n"
"Laurent Jonqueres - Occitan localization\n"
"Laurent Mutricy - HTTP interface fixes\n"
"Leo Spalteholz - Qt interface design\n"
"Loox Thefuture - Media key in X11 vout\n"
"Lorena Gomes - Catalan translation\n"
"Ludovic Fauvet - Qt4 patch\n"
"Lukas Durfina - Qt4: full screen controller. Teletext button fix. Various fixes.\n"
"Luqman Hakim - Indonesian translation\n"
"Mahrazi Mohd Kamal - Malay Translation\n"
"Malte Tancred - VLCKit patch for URLs\n"
"Marc Nolette - PVR support in DirectShow input\n"
"Marco Munderloh - HTTP fix for Win32 to URL filenames\n"
"Marián Hikaník - Slovak localisation\n"
"Mark Gritter - fix for netlist packet leak in demuxPSI\n"
"Marko Uskokovic - Serbian localisation\n"
"Markus Kern - video output window fixes (win32)\n"
"Markus Kuespert - BeOS CSS support\n"
"Martin Hamrle - PulseAudio output module\n"
"Martin Kahr - Apple Remote support\n"
"Matej Urbančič - Slovenian translation\n"
"Mateus Krepsky Ludwich - rc interface mosaic-order callback\n"
"Mathias C. Berens | welcome-soft - German translation\n"
"Mathias Kretschmer - IP Multicast support\n"
"Mats Rojestal - compilation fixes for Solaris 9\n"
"Matthias P. Nowak - ALSA 5.1 fix\n"
"Matthieu Lochegnies - MPEG audio emphasis fix\n"
"Max Rudberg - Mac OS X controller art (v0.7.0)\n"
"Md. Rezwan Shahid - Bengali translation\n"
"Meelad Zakaria - Persian localisation\n"
"Michael Mondragon - ncurses compilation fix\n"
"Michael Ploujnikov - Spelling fix\n"
"Michał Trzebiatowski - Polish translation\n"
"Michel Lanners - fixed typos and AltiVec detection\n"
"Mickael Hoerdt - IPv6 SSM multicast patch\n"
"Miguel Angel Cabrera - RTMP access patch\n"
"Mike Schrag - directx device selection\n"
"Mikko Hirvonen - Firefox-1.5.x development configure patch\n"
"Miroslav Oujeský - Czech translation\n"
"Mirsal Ennaime - D-Bus ameliorations\n"
"Moritz Bunkus - Matroska patches\n"
"Morten Brix Pedersen - Danish translation\n"
"Myckel Habets - Dutch translation\n"
"Namhyung Kim - Korean translation\n"
"Nilmoni Deb - autoconf and Makefile fixes\n"
"Olivier Aubert - clone list patch\n"
"Olivier Houchard - UDP & HTTP access output fix, ffmpeg mux fix\n"
"Olivier Pomel - original VLC code\n"
"Omer Ensari - Kurmanji (Kurdish) translation\n"
"Ondrej Kuda aka Albert - HTTP interface tips and fixes\n"
"Otto Kekäläinen - Finnish translation \n"
"Øyvind Kolbu - FreeBSD patches\n"
"Patrick Horn - DirectShow patch\n"
"Patrick McLean - Libcdio update patch\n"
"Paul Corke - pvr and dv patches for newer drivers and hardware\n"
"Pauline Castets - NSIS fixes and i18n\n"
"Paul Mackerras - AltiVec IDCT and motion\n"
"Petr Vacek - FTP cleartext authentication\n"
"Philippe A. aka \"Lotesdelère\" - Numerous testing and bug reporting\n"
"Philippe Van Hecke - SAP header hash patch\n"
"Pierre d'Herbemont - Compile fix\n"
"Pierre-Luc Beaudoin - Vorbis 9 channels patch, Jack input fixes.\n"
"Pierre Marc Dumuid - Playlist patches\n"
"Pierre Ynard - WinCE and win32 fixes\n"
"Pittayakom Saingtong - Thai localisation\n"
"Przemyslaw Fiala - MMS/TCP fix\n"
"Régis Duchesne - original VLC code\n"
"Rémi Duraffort - various QT4 patches, lots of memory leaks and bug fixes\n"
"Remco Poortinga - IPv6 multicast patch\n"
"Rene Gollent - BeOS interface fix\n"
"Richard Hosking - v4l2 support\n"
"Richard Øiestad - VLC cone graphics (v0.7.x)\n"
"Rob Casey - Amino RTSP fix\n"
"Robson Braga Araujo - UPnP discovery XML fix\n"
"Roine Gustafsson - spudec bug fixes\n"
"Roman Bednarek - MPL2 subtitles support\n"
"Roustam Ghizdatov - Russian translation\n"
"Rudolf Cornelissen - BeOS fixes\n"
"Salar Khalilzadeh\" - Persian translation\n"
"Sašo Kiselkov - RTSP session timeout fix for some STBs, multipass x264 patch\n"
"Scott Caudle - Visualization, WX improvements\n"
"Sebastian Jenny - AAC decoding channel ordering fix.\n"
"Sebastien Chaumat - YOPY port tests\n"
"Sidney Doria - Brazilian Portuguese localisation\n"
"Simon Damkjær Andersen - playmode icons and the entire Fullscreen Panel design for the OSX GUI (v0.8.6)\n"
"Søren Bøg - dynamicoverlays\n"
"Srikanth Raju - Chorus flanger audio filter\n"
"Stefán Freyr Stefánsson - Qt4 speed slider\n"
"Steve Brown - fix for optional PES size bug\n"
"Steve Lhomme - MSVC fixes and Matroska enhancements\n"
"Steven M. Schultz - BSD/OS port\n"
"Steven Sheehy - wxWidgets interface fix\n"
"Tadashi Jokagi - Japanese translation\n"
"Tanguy Krotoff - LibVLC cleanup and fix.\n"
"Tapio Hiltunen - Maemo X11 enhancements\n"
"Tim 'O Callaghan - pvr input cleaning patch\n"
"Tim Schuerewegen - contrib fixes\n"
"Thomas De Rocker - Dutch translation\n"
"Thomas Graf - gettext support, German translation\n"
"Thomas L. Wood - fixed a bug in QuantMatrixExtension\n"
"Thomas Mühlgrabner - AAC fixes.\n"
"Thomas Parmelan - mosaic user-defined offsets for substreams\n"
"Tom Bigelajzen - Interface icons and help with web design\n"
"Tomáš Chvátal - Czech Localisation\n"
"Tong Ka Man - playlist_Clear addition\n"
"Tòni Galhard - Occitan translation\n"
"Torsten Spindler - Script to set vlc as default player on GNOME desktops.\n"
"Udo Richter - Trancode padding / cropping\n"
"Valek Filippov - Russian translation\n"
"Vicente Jimenez Aguilar - Spanish translation\n"
"Vincent Dimar - WxWidgets online help patch\n"
"Vincent Penquerc'h - Kate subtitle decoder module\n"
"Vincent van den Heuvel - OSX about window artwork (v0.8.4)\n"
"Vincenzo Reale - Italian translation\n"
"Vitalijus Slavinskas - nsv patches\n"
"Vitaly V. Bursov <vitalyvb at ukr dot net>\n"
"Vladimir Chernyshov - MMX motion optimizations\n"
"Vladimir Yermolayev -- Russian translation\n"
"Wade Majors - BeOS icon integration, debugging and fixes\n"
"Wallace Wadge - multiple programs TS mux\n"
"Wang Bo - Real support improvements.\n"
"Watanabe Go - fix for non-ASCII filenames\n"
"Wei Mingzhi - Simplied Chinese translation\n"
"William Hawkins - Speex RTP payload format\n"
"Xavier Maillard - audio converters\n"
"Xavier Marchesini - Win32 fixes\n"
"Xènia Albà Cantero - Catalan translation\n"
"Ye zhang - Fix for VLM RTSP concurent LEAVE make VLC crash\n"
"Yuehua Zhao - real video codec\n"
"Yves Duret - RPM packages\n"
"Zhang Tong - Chinese translation\n"
"\n"
"\n"
"Some VLC plugins use external libraries and makes extensive use of the following persons' or companies' code:\n"
"\n"
"FFmpeg - Copyright (c) 2000-2007 Fabrice Bellard, et al.\n"
"liba52 - Aaron Holtzman & Michel Lespinasse, et al.\n"
"FAAD2 - \"Code from FAAD2 is copyright (c) Nero AG, www.nero.com\"\n"
"FAAC - Menno Bakker, Krzysztof Nikiel & The individual contributors\n"
"libmpeg2 - Aaron Holtzman & Michel Lespinasse, et al.\n"
"ogg, theora, vorbis - Monty & the Xiph.org Foundation\n"
"flac - Josh Coalson et al.\n"
;
static const char psz_authors[] =
"Laurent Aimar\n"
"Marc Ariberti\n"
"Stephan Assmus\n"
"Olivier Aubert\n"
"Sigmund Augdal Helberg\n"
"Pierre Baillet\n"
"Gildas Bazin\n"
"Rocky Bernstein\n"
"Johan Bilien\n"
"Stéphane Borel\n"
"Arnaud de Bossoreille de Ribou\n"
"Filippo Carone \n"
"Rafaël \"Hanz, David\" Carré\n"
"Tony Castley\n"
"Antoine Cellerier\n"
"Renaud Dartus\n"
"Cyril Deguet\n"
"Rémi Denis-Courmont\n"
"Colin Delacroix\n"
"Pierre d'Herbemont\n"
"Boris Dorès\n"
"Jean-Marc Dressler\n"
"Henri Fallon\n"
"Andrew Flintham\n"
"Damien Fouilleul\n"
"Alexis Guillard\n"
"Gerald Hansink\n"
"Shane Harper\n"
"Dugal Harris\n"
"Derk-Jan Hartman\n"
"Gaël Hendryckx\n"
"Samuel Hocevar\n"
"Eugenio Jarosiewicz\n"
"Jon Lech Johansen\n"
"Michel Kaempf\n"
"Jean-Baptiste Kempf\n"
"Pavlov Konstantin\n"
"Felix Paul Kühne\n"
"Simon Latapie\n"
"Pascal Levesque\n"
"Christophe Massiot\n"
"Loïc Minier\n"
"Christophe Mutricy\n"
"Florian G. Pflug\n"
"Heiko Panther\n"
"Vincent Penne\n"
"Eric Petit\n"
"Benjamin Pracht\n"
"Emmanuel Puig\n"
"Frédéric Ruget\n"
"Jean-Paul Saman\n"
"Arnaud Schauly\n"
"Vincent Seguin\n"
"Ken Self\n"
"Richard Shepherd\n"
"Clément Stenac\n"
"Peter Surda\n"
"Olivier Teulière\n"
"Yuehua Zhao\n"
"Bo Wang\n"
;
